package com.newx.pojo;

import java.util.Date;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_id
     *
     * @mbggenerated
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_name
     *
     * @mbggenerated
     */
    private String paperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_author
     *
     * @mbggenerated
     */
    private Integer paperAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.last_time
     *
     * @mbggenerated
     */
    private Integer lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.token
     *
     * @mbggenerated
     */
    private Integer token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.join_times
     *
     * @mbggenerated
     */
    private Integer joinTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.min_score
     *
     * @mbggenerated
     */
    private Integer minScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.max_score
     *
     * @mbggenerated
     */
    private Integer maxScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.pass_num
     *
     * @mbggenerated
     */
    private Integer passNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.avg_score
     *
     * @mbggenerated
     */
    private Float avgScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.delete
     *
     * @mbggenerated
     */
    private Integer delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    public Paper(Integer paperId, String paperName, Integer paperAuthor, Date startTime, Integer lastTime, Integer status, Integer token, Integer joinTimes, Integer minScore, Integer maxScore, Integer passNum, Float avgScore, Integer delete) {
        this.paperId = paperId;
        this.paperName = paperName;
        this.paperAuthor = paperAuthor;
        this.startTime = startTime;
        this.lastTime = lastTime;
        this.status = status;
        this.token = token;
        this.joinTimes = joinTimes;
        this.minScore = minScore;
        this.maxScore = maxScore;
        this.passNum = passNum;
        this.avgScore = avgScore;
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    public Paper() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_id
     *
     * @return the value of paper.paper_id
     *
     * @mbggenerated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_id
     *
     * @param paperId the value for paper.paper_id
     *
     * @mbggenerated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_name
     *
     * @return the value of paper.paper_name
     *
     * @mbggenerated
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_name
     *
     * @param paperName the value for paper.paper_name
     *
     * @mbggenerated
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName == null ? null : paperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_author
     *
     * @return the value of paper.paper_author
     *
     * @mbggenerated
     */
    public Integer getPaperAuthor() {
        return paperAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_author
     *
     * @param paperAuthor the value for paper.paper_author
     *
     * @mbggenerated
     */
    public void setPaperAuthor(Integer paperAuthor) {
        this.paperAuthor = paperAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.start_time
     *
     * @return the value of paper.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.start_time
     *
     * @param startTime the value for paper.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.last_time
     *
     * @return the value of paper.last_time
     *
     * @mbggenerated
     */
    public Integer getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.last_time
     *
     * @param lastTime the value for paper.last_time
     *
     * @mbggenerated
     */
    public void setLastTime(Integer lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.status
     *
     * @return the value of paper.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.status
     *
     * @param status the value for paper.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.token
     *
     * @return the value of paper.token
     *
     * @mbggenerated
     */
    public Integer getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.token
     *
     * @param token the value for paper.token
     *
     * @mbggenerated
     */
    public void setToken(Integer token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.join_times
     *
     * @return the value of paper.join_times
     *
     * @mbggenerated
     */
    public Integer getJoinTimes() {
        return joinTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.join_times
     *
     * @param joinTimes the value for paper.join_times
     *
     * @mbggenerated
     */
    public void setJoinTimes(Integer joinTimes) {
        this.joinTimes = joinTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.min_score
     *
     * @return the value of paper.min_score
     *
     * @mbggenerated
     */
    public Integer getMinScore() {
        return minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.min_score
     *
     * @param minScore the value for paper.min_score
     *
     * @mbggenerated
     */
    public void setMinScore(Integer minScore) {
        this.minScore = minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.max_score
     *
     * @return the value of paper.max_score
     *
     * @mbggenerated
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.max_score
     *
     * @param maxScore the value for paper.max_score
     *
     * @mbggenerated
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.pass_num
     *
     * @return the value of paper.pass_num
     *
     * @mbggenerated
     */
    public Integer getPassNum() {
        return passNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.pass_num
     *
     * @param passNum the value for paper.pass_num
     *
     * @mbggenerated
     */
    public void setPassNum(Integer passNum) {
        this.passNum = passNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.avg_score
     *
     * @return the value of paper.avg_score
     *
     * @mbggenerated
     */
    public Float getAvgScore() {
        return avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.avg_score
     *
     * @param avgScore the value for paper.avg_score
     *
     * @mbggenerated
     */
    public void setAvgScore(Float avgScore) {
        this.avgScore = avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.delete
     *
     * @return the value of paper.delete
     *
     * @mbggenerated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.delete
     *
     * @param delete the value for paper.delete
     *
     * @mbggenerated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }
}