package com.newx.pojo;

public class PaperQuestion extends PaperQuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.mark
     *
     * @mbggenerated
     */
    private Integer mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.delete
     *
     * @mbggenerated
     */
    private Integer delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    public PaperQuestion(Integer paperId, Integer questionId, Integer mark, Integer delete) {
        super(paperId, questionId);
        this.mark = mark;
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    public PaperQuestion() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.mark
     *
     * @return the value of paper_question.mark
     *
     * @mbggenerated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.mark
     *
     * @param mark the value for paper_question.mark
     *
     * @mbggenerated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.delete
     *
     * @return the value of paper_question.delete
     *
     * @mbggenerated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.delete
     *
     * @param delete the value for paper_question.delete
     *
     * @mbggenerated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }
}