package com.newx.pojo;

public class QuestionWithBLOBs extends Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_content
     *
     * @mbggenerated
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    public QuestionWithBLOBs(Integer questionId, Integer questionType, Integer subcategoryId, String option1, String option2, String option3, String option4, String option5, Integer level, Integer delete, String questionContent, String answer) {
        super(questionId, questionType, subcategoryId, option1, option2, option3, option4, option5, level, delete);
        this.questionContent = questionContent;
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    public QuestionWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_content
     *
     * @return the value of question.question_content
     *
     * @mbggenerated
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_content
     *
     * @param questionContent the value for question.question_content
     *
     * @mbggenerated
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent == null ? null : questionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}