package com.newx.pojo;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_type
     *
     * @mbggenerated
     */
    private Integer questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.subcategory_id
     *
     * @mbggenerated
     */
    private Integer subcategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_1
     *
     * @mbggenerated
     */
    private String option1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_2
     *
     * @mbggenerated
     */
    private String option2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_3
     *
     * @mbggenerated
     */
    private String option3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_4
     *
     * @mbggenerated
     */
    private String option4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_5
     *
     * @mbggenerated
     */
    private String option5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.delete
     *
     * @mbggenerated
     */
    private Integer delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    public Question(Integer questionId, Integer questionType, Integer subcategoryId, String option1, String option2, String option3, String option4, String option5, Integer level, Integer delete) {
        this.questionId = questionId;
        this.questionType = questionType;
        this.subcategoryId = subcategoryId;
        this.option1 = option1;
        this.option2 = option2;
        this.option3 = option3;
        this.option4 = option4;
        this.option5 = option5;
        this.level = level;
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    public Question() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_id
     *
     * @return the value of question.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_id
     *
     * @param questionId the value for question.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_type
     *
     * @return the value of question.question_type
     *
     * @mbggenerated
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_type
     *
     * @param questionType the value for question.question_type
     *
     * @mbggenerated
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.subcategory_id
     *
     * @return the value of question.subcategory_id
     *
     * @mbggenerated
     */
    public Integer getSubcategoryId() {
        return subcategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.subcategory_id
     *
     * @param subcategoryId the value for question.subcategory_id
     *
     * @mbggenerated
     */
    public void setSubcategoryId(Integer subcategoryId) {
        this.subcategoryId = subcategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_1
     *
     * @return the value of question.option_1
     *
     * @mbggenerated
     */
    public String getOption1() {
        return option1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_1
     *
     * @param option1 the value for question.option_1
     *
     * @mbggenerated
     */
    public void setOption1(String option1) {
        this.option1 = option1 == null ? null : option1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_2
     *
     * @return the value of question.option_2
     *
     * @mbggenerated
     */
    public String getOption2() {
        return option2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_2
     *
     * @param option2 the value for question.option_2
     *
     * @mbggenerated
     */
    public void setOption2(String option2) {
        this.option2 = option2 == null ? null : option2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_3
     *
     * @return the value of question.option_3
     *
     * @mbggenerated
     */
    public String getOption3() {
        return option3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_3
     *
     * @param option3 the value for question.option_3
     *
     * @mbggenerated
     */
    public void setOption3(String option3) {
        this.option3 = option3 == null ? null : option3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_4
     *
     * @return the value of question.option_4
     *
     * @mbggenerated
     */
    public String getOption4() {
        return option4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_4
     *
     * @param option4 the value for question.option_4
     *
     * @mbggenerated
     */
    public void setOption4(String option4) {
        this.option4 = option4 == null ? null : option4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_5
     *
     * @return the value of question.option_5
     *
     * @mbggenerated
     */
    public String getOption5() {
        return option5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_5
     *
     * @param option5 the value for question.option_5
     *
     * @mbggenerated
     */
    public void setOption5(String option5) {
        this.option5 = option5 == null ? null : option5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.level
     *
     * @return the value of question.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.level
     *
     * @param level the value for question.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.delete
     *
     * @return the value of question.delete
     *
     * @mbggenerated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.delete
     *
     * @param delete the value for question.delete
     *
     * @mbggenerated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }
}