package com.newx.pojo;

public class UserSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_1
     *
     * @mbggenerated
     */
    private Integer skill1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_2
     *
     * @mbggenerated
     */
    private Integer skill2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_3
     *
     * @mbggenerated
     */
    private Integer skill3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_4
     *
     * @mbggenerated
     */
    private Integer skill4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_5
     *
     * @mbggenerated
     */
    private Integer skill5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_6
     *
     * @mbggenerated
     */
    private Integer skill6;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    public UserSkill(Integer userId, Integer skill1, Integer skill2, Integer skill3, Integer skill4, Integer skill5, Integer skill6) {
        this.userId = userId;
        this.skill1 = skill1;
        this.skill2 = skill2;
        this.skill3 = skill3;
        this.skill4 = skill4;
        this.skill5 = skill5;
        this.skill6 = skill6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    public UserSkill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.user_id
     *
     * @return the value of user_skill.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.user_id
     *
     * @param userId the value for user_skill.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_1
     *
     * @return the value of user_skill.skill_1
     *
     * @mbggenerated
     */
    public Integer getSkill1() {
        return skill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_1
     *
     * @param skill1 the value for user_skill.skill_1
     *
     * @mbggenerated
     */
    public void setSkill1(Integer skill1) {
        this.skill1 = skill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_2
     *
     * @return the value of user_skill.skill_2
     *
     * @mbggenerated
     */
    public Integer getSkill2() {
        return skill2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_2
     *
     * @param skill2 the value for user_skill.skill_2
     *
     * @mbggenerated
     */
    public void setSkill2(Integer skill2) {
        this.skill2 = skill2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_3
     *
     * @return the value of user_skill.skill_3
     *
     * @mbggenerated
     */
    public Integer getSkill3() {
        return skill3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_3
     *
     * @param skill3 the value for user_skill.skill_3
     *
     * @mbggenerated
     */
    public void setSkill3(Integer skill3) {
        this.skill3 = skill3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_4
     *
     * @return the value of user_skill.skill_4
     *
     * @mbggenerated
     */
    public Integer getSkill4() {
        return skill4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_4
     *
     * @param skill4 the value for user_skill.skill_4
     *
     * @mbggenerated
     */
    public void setSkill4(Integer skill4) {
        this.skill4 = skill4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_5
     *
     * @return the value of user_skill.skill_5
     *
     * @mbggenerated
     */
    public Integer getSkill5() {
        return skill5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_5
     *
     * @param skill5 the value for user_skill.skill_5
     *
     * @mbggenerated
     */
    public void setSkill5(Integer skill5) {
        this.skill5 = skill5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_6
     *
     * @return the value of user_skill.skill_6
     *
     * @mbggenerated
     */
    public Integer getSkill6() {
        return skill6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_6
     *
     * @param skill6 the value for user_skill.skill_6
     *
     * @mbggenerated
     */
    public void setSkill6(Integer skill6) {
        this.skill6 = skill6;
    }
}