package com.newx.pojo;

public class UserQuestionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_questions.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_questions.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    public UserQuestionsKey(Integer userId, Integer questionId) {
        this.userId = userId;
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    public UserQuestionsKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_questions.user_id
     *
     * @return the value of user_questions.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_questions.user_id
     *
     * @param userId the value for user_questions.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_questions.question_id
     *
     * @return the value of user_questions.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_questions.question_id
     *
     * @param questionId the value for user_questions.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
}