package com.newx.pojo;

public class UserQuestions extends UserQuestionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_questions.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    public UserQuestions(Integer userId, Integer questionId, String note) {
        super(userId, questionId);
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    public UserQuestions() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_questions.note
     *
     * @return the value of user_questions.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_questions.note
     *
     * @param note the value for user_questions.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}