package com.newx.pojo;

public class UserAnswerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.paper_id
     *
     * @mbggenerated
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbggenerated
     */
    public UserAnswerKey(Integer userId, Integer paperId, Integer questionId) {
        this.userId = userId;
        this.paperId = paperId;
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbggenerated
     */
    public UserAnswerKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.user_id
     *
     * @return the value of user_answer.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.user_id
     *
     * @param userId the value for user_answer.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.paper_id
     *
     * @return the value of user_answer.paper_id
     *
     * @mbggenerated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.paper_id
     *
     * @param paperId the value for user_answer.paper_id
     *
     * @mbggenerated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.question_id
     *
     * @return the value of user_answer.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.question_id
     *
     * @param questionId the value for user_answer.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
}