package com.newx.dao;

import com.newx.pojo.PaperQuestion;
import com.newx.pojo.PaperQuestionKey;

public interface PaperQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PaperQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int insert(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int insertSelective(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    PaperQuestion selectByPrimaryKey(PaperQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaperQuestion record);
}