package com.newx.dao;

import com.newx.pojo.Subcategory;

public interface SubcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer subcategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated
     */
    int insert(Subcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated
     */
    int insertSelective(Subcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated
     */
    Subcategory selectByPrimaryKey(Integer subcategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Subcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Subcategory record);
}