package com.newx.dao;

import com.newx.pojo.UserSkill;

public interface UserSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    int insert(UserSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    int insertSelective(UserSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    UserSkill selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserSkill record);
}