package com.newx.dao;

import com.newx.pojo.UserQuestions;
import com.newx.pojo.UserQuestionsKey;

public interface UserQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserQuestionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    int insert(UserQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    int insertSelective(UserQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    UserQuestions selectByPrimaryKey(UserQuestionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_questions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserQuestions record);
}